### ISSUE TITLE
Profile json reset to default after upgrade to 1.1.1.1

### ISSUE THREAD

**Issue by Spheres-cu** [Melv1no/Flow.Launcher.Plugin.easyssh#1]
After upgrade the plugin a new folder is create with the number of this update and the profiles.json is reset to default

**Comment by Melv1no** [comment]
Fixed with commit 7027d962d26beb426c1d76921642b98fc1319e29

The new directory for profiles.json is .ssh

**Comment by Spheres-cu** [comment]
1.1.1.2 now creates the profiles.json file in the user's .ssh folder but still does not update the previous configuration

**Comment by Melv1no** [comment]
You want a patch to update the configuration olded stored in the plugin folder ?

**Comment by Spheres-cu** [comment]
> You want a patch to update the configuration olded stored in the plugin folder ?
 exactly, because every time I update that configuration is lost

**Comment by Melv1no** [comment]
If you use the new ssh profiles file that not working ? You update and his new profile file is reset ?

**Comment by Spheres-cu** [comment]
> If you use the new ssh profiles file that not working ? You update and his new profile file is reset ?

Yes, it does reset

**Comment by Melv1no** [comment]
what version you actually use ?

**Comment by Spheres-cu** [comment]
> what version you actually use ?

1.1.1.2 but previous saved the json profile and manually updated it

**Comment by Melv1no** [comment]
I close this issue, the problem was patch.

Now the configuration is stored at C:\users\<username>\profiles.json
